@startuml
Actor Pengguna
Boundary Login
Boundary LupaPassword
Control ResetPassword
Entity DataUser
Pengguna -> Login:btnLupaPassword.setOnClickListener()
Login -> LupaPassword:intent(this,LupaPassword.class)
LupaPassword -> LupaPassword:onCreate()
LupaPassword -> Pengguna: Menampilkan Form Reset Password
Pengguna->LupaPassword:btnReset.setOnClickListener()
LupaPassword->ResetPassword:getEmail()
ResetPassword->DataUser:setNewPassword()
DataUser->ResetPassword:Berhasil Mereset Password
ResetPassword->LupaPassword:Berhasil Mereset Password
LupaPassword->Login:intent(this,LoginActivity.class)
Login->Pengguna:Menampilkan FeedBack Untuk Memeriksa Email
@enduml